name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract Username from Repository
      id: extract-username
      run: |
        REPO=${{ github.repository }}
        USERNAME=$(echo $REPO | cut -d'/' -f1)
        echo "USERNAME=$USERNAME" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ env.USERNAME }}/file-transfer:latest
    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ env.USERNAME }}/file-transfer:latest